### ISSUE TITLE
Overlay icons don't stick with window when workspace sidebar expands

### ISSUE THREAD

**Issue by InfernoZeus** [sustmi/gnome-shell-extensions-sustmi#29] opened 2015-02-11 16:16 UTC
In the Gnome overlay, the workspace sidebar is automatically (almost) hidden to the side of the screen when only the main workspace has windows present. Dragging a window towards that sidebar causes it to pop open shifting all of the windows. The overlaid icons don't shift with them properly. 

You can see it here: http://www.gfycat.com/ShowyShrillAlligatorsnappingturtle

I'm running GNOME Shell 3.14.3.

**Comment by sustmi** [comment] 2015-09-20 12:52
Hi @InfernoZeus, do you still use GNOME Shell 3.14?
I cannot reproduce the issue in 3.16.3.

**Comment by synapsos** [comment] 2016-04-27 17:57
This is still an issue in 3.18. To reproduce this behavior:
* In Gnome Tweak Tool set Workspaces to *Dynamic*
* Put all your windows on the first workspace (other ones empty)
* Click and drag a window in overview

The panel on the right will pop out and push all windows to the left, while the icons stay in place.
I fixed it with [this addon](https://extensions.gnome.org/extension/820/minimum-workspaces/) or you can just set Workspaces to *Static*.

**Comment by sustmi** [comment] 2016-04-30 07:23
I have Gnome Shell 3.18.4, but my right panel does not pop out. It is fixed and fully visible the whole time.
Do you have any other plugins installed and what is your distribution? Mine is Fedora 23.

**Comment by sustmi** [comment] 2016-09-28 17:57
On Gnome Shell 3.20.4 there is pop-up right panel in window overview however I cannot reproduce the issue. Everything works well for me. I am closing the issue now. If you still have problems with it try to upgrade to Gnome Shell 3.20.

**Closed by sustmi** 2016-09-28 17:57 UTC
