### ISSUE TITLE
windowoverlay-icons: icon positions are sometimes reset

### ISSUE THREAD

**Issue by libcg** [sustmi/gnome-shell-extensions-sustmi#28] opened 2015-01-28 18:49 UTC
Icons positions are randomly reset (maybe one time every 30 minutes, not sure). When this happens they all transition from the top left corner of the screen to their correct position. Quite annoying!

**Comment by sustmi** [comment] 2015-01-30 21:52
Hi Clément. I have also encountered this glitch.
Unfortunately, as you said it happens randomly maybe once in 30 minutes, so it is very hard to debug.
I am logging ```updatePositions()```, but I have already spent 10 minutes unsuccessfully trying to reproduce it. :|

**Comment by libcg** [comment] 2015-01-31 01:01
I remember old gnome-shell <=3.12 doing the same thing for window thumbnails, but it has been fixed in 3.14, I think.

**Comment by sustmi** [comment] 2015-09-20 12:56
Hi @libcg, does this still happen to you?
Maybe it was fixed with new version of GNOME Shell (I use 3.16.3 now).

**Comment by libcg** [comment] 2015-09-20 15:07
I'm using 3.17.90 right now, so no extensions for me. I will try it when I can, but last I remember, it wasn't fixed.

**Comment by sustmi** [comment] 2016-09-28 18:01
I am closing the issue now. I am not sure if the problem is in my plugin, other plugins or Gnome Shell itself. Maybe there still are some glitches but I think they are so rare that it is not worth hunting the bug.
If you feel this has to be fixed, let me know.

**Closed by sustmi** 2016-09-28 18:01 UTC
